### ISSUE TITLE
wrong coloring

### ISSUE THREAD

**Issue by craig** [SpeckiJ/Hochwasser#2]
While your code is fast, it does not accurately display pictures, e.g. even this one: https://github.com/SpeckiJ/Hochwasser/raw/master/benchmarks/benchmark_x280.png

Text (e.g. "Hochwasser") is shown in red.
Tested with go version go1.11.6 linux/amd64.

**Comment by SpeckiJ** [comment]
Thanks for the report 👍 I will look into it asap (may take a while tho).

I guess our wonky readout function for converting colors into text is the cause for this: https://github.com/SpeckiJ/Hochwasser/blob/91826ea600dd20013e72e00fe95698e9b8bae964/main.go#L103
